#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ -n "$1" ]]; then
  LOCAL_GO="$1"
  shift
else
  LOCAL_GO=../sam-go
fi

echo "==> Linking with local directory"
go mod edit -replace github.com/DefinitelyATestOrg/sam-go="$LOCAL_GO"
